version: '3'
services:
   nginx: 
    image: nginx:1.15-alpine
    # apache is running on port 80 but we want to expose this to port 4000 on our local machine
    #container_name: nginx_1
    ports:
    - "80:80"
    - "443:443"
   
    volumes:
     #- ./000-default.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
     # - ./nginx/rpi-iot.conf:/etc/nginx/conf.d/rpi-iot.conf
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

   certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
